#!/bin/bash

# A shell script to kill the PiMessage server daemon
# Note: this should only be used during development and it should not be
# necessary as part of normal usage of PiMessage. The daemon is normally
# intended to run in the background

killall pmdaemon.py
exit $?
